### ISSUE TITLE
Add units in retention time command help

### ISSUE THREAD

**Issue by thody** [heroku/heroku-kafka-jsplugin#99]
Would be good to tell the user what unit of time we're expecting here.

`kafka:topics:retention-time TOPIC VALUE [CLUSTER]      #  configures topic retention time in Kafka`

**Comment by uhoh-itsmaciek** [comment]
Wording suggestions @thody or @rand? The help for command itself (rather than this description, which is used in the top-level `kafka` help) does give examples with units. We can say "in milliseconds", which it is if you don't provide units, but that may encourage people to try to calculate the milliseconds rather than look up help for the command. I've always thought of the topic-level help as a general overview of the commands available, so you can find the right one at a glance, and then dig in for command-specific help (thoughts @dickeyxxx?). If we can make this clearer and stay within the 80-char recommended limit, I'm all for that but I'm not sure how to indicate the supported interval syntax within that. Maybe something like `configures topic retention time (e.g., '10d') in Kafka`? Also while we're at it, should we drop `in Kafka`--that's kind of obvious, no?

**Comment by thody** [comment]
@uhoh-itsmaciek hmm, I didn't realize we support user specified units. That definitely makes this a little trickier.

To get it out of the way, you're right, I think we can definitely drop `in Kafka`, it's superfluous.

I like the example approach, but I think we need at least two examples, with different units. Otherwise, I think users would just assume we only support specifying in days.

ie. `configures topic retention time (e.g. 10h, 3d, 25m)`

Thoughts @rand?

**Comment by rand** [comment]
I like @thody's example. Solid.

**Comment by idan** [comment]
DHC only permits days and hours — do we need other units in the CLI?

**Comment by uhoh-itsmaciek** [comment]
Good call, probably not (certainly not in the example, right?).

**Comment by thody** [comment]
In general, I don't think it's unreasonable for the CLI to offer a superset of functionality relative to DHC. Is there any cost to keeping the added flexibility?

The rationale for DHC wasn't that we need to prevent users from specifying in other units, but that it seemed less useful to include units in the dropdown that would require humans to do silly math (e.g. how many minutes in a day and a half?).

**Comment by rand** [comment]
I like the CLI being a superset of DHC, but worry about values being set via CLI that _can't_ be set via DHC, as it could create some weird editing/display cases.
